# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(704, 910)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.toolUndo = QtWidgets.QToolButton(self.frame)
        self.toolUndo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img-undo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolUndo.setIcon(icon)
        self.toolUndo.setObjectName("toolUndo")
        self.horizontalLayout_8.addWidget(self.toolUndo)
        self.toolRedo = QtWidgets.QToolButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img-redo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolRedo.setIcon(icon1)
        self.toolRedo.setObjectName("toolRedo")
        self.horizontalLayout_8.addWidget(self.toolRedo)
        self.toolCopy = QtWidgets.QToolButton(self.frame)
        self.toolCopy.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img-copy"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolCopy.setIcon(icon2)
        self.toolCopy.setCheckable(False)
        self.toolCopy.setObjectName("toolCopy")
        self.horizontalLayout_8.addWidget(self.toolCopy)
        self.toolCut = QtWidgets.QToolButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img-cut"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolCut.setIcon(icon3)
        self.toolCut.setCheckable(False)
        self.toolCut.setObjectName("toolCut")
        self.horizontalLayout_8.addWidget(self.toolCut)
        self.toolPaste = QtWidgets.QToolButton(self.frame)
        self.toolPaste.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img-paste"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolPaste.setIcon(icon4)
        self.toolPaste.setCheckable(False)
        self.toolPaste.setObjectName("toolPaste")
        self.horizontalLayout_8.addWidget(self.toolPaste)
        self.toolBold = QtWidgets.QToolButton(self.frame)
        self.toolBold.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img-bold"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBold.setIcon(icon5)
        self.toolBold.setCheckable(False)
        self.toolBold.setObjectName("toolBold")
        self.horizontalLayout_8.addWidget(self.toolBold)
        self.toolItalic = QtWidgets.QToolButton(self.frame)
        self.toolItalic.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img-italics"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolItalic.setIcon(icon6)
        self.toolItalic.setCheckable(False)
        self.toolItalic.setObjectName("toolItalic")
        self.horizontalLayout_8.addWidget(self.toolItalic)
        self.toolUnderline = QtWidgets.QToolButton(self.frame)
        self.toolUnderline.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolUnderline.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img-underline"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolUnderline.setIcon(icon7)
        self.toolUnderline.setCheckable(False)
        self.toolUnderline.setObjectName("toolUnderline")
        self.horizontalLayout_8.addWidget(self.toolUnderline)
        self.toolHeader = QtWidgets.QToolButton(self.frame)
        self.toolHeader.setToolTipDuration(-1)
        self.toolHeader.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img-h1"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolHeader.setIcon(icon8)
        self.toolHeader.setCheckable(False)
        self.toolHeader.setObjectName("toolHeader")
        self.horizontalLayout_8.addWidget(self.toolHeader)
        self.toolOList = QtWidgets.QToolButton(self.frame)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img-ol"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolOList.setIcon(icon9)
        self.toolOList.setCheckable(False)
        self.toolOList.setObjectName("toolOList")
        self.horizontalLayout_8.addWidget(self.toolOList)
        self.toolUList = QtWidgets.QToolButton(self.frame)
        self.toolUList.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img-ul"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolUList.setIcon(icon10)
        self.toolUList.setCheckable(False)
        self.toolUList.setObjectName("toolUList")
        self.horizontalLayout_8.addWidget(self.toolUList)
        self.toolLink = QtWidgets.QToolButton(self.frame)
        self.toolLink.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img-link"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolLink.setIcon(icon11)
        self.toolLink.setCheckable(True)
        self.toolLink.setObjectName("toolLink")
        self.horizontalLayout_8.addWidget(self.toolLink)
        self.toolUnlink = QtWidgets.QToolButton(self.frame)
        self.toolUnlink.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img-unlink"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolUnlink.setIcon(icon12)
        self.toolUnlink.setCheckable(False)
        self.toolUnlink.setObjectName("toolUnlink")
        self.horizontalLayout_8.addWidget(self.toolUnlink)
        self.verticalLayout_4.addWidget(self.frame)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        self.buttonBox.accepted.connect(Form.save)
        self.buttonBox.rejected.connect(Form.warn)
        self.toolBold.clicked.connect(Form.bold)
        self.toolCopy.clicked.connect(self.textEdit.copy)
        self.toolCut.clicked.connect(self.textEdit.cut)
        self.toolHeader.clicked.connect(Form.header)
        self.toolItalic.clicked.connect(Form.italic)
        self.toolLink.clicked.connect(Form.link)
        self.toolOList.clicked.connect(Form.orderedList)
        self.toolPaste.clicked.connect(self.textEdit.paste)
        self.toolUList.clicked.connect(Form.unorderedList)
        self.toolUnderline.clicked.connect(Form.underline)
        self.toolUnlink.clicked.connect(Form.unlink)
        self.toolUndo.clicked.connect(self.textEdit.undo)
        self.toolRedo.clicked.connect(self.textEdit.redo)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolUndo.setToolTip(_translate("Form", "Undo change (Ctrl+Z)"))
        self.toolUndo.setShortcut(_translate("Form", "Ctrl+Z"))
        self.toolRedo.setToolTip(_translate("Form", "Redo change (Ctrl+Y)"))
        self.toolRedo.setText(_translate("Form", "..."))
        self.toolRedo.setShortcut(_translate("Form", "Ctrl+Y"))
        self.toolCopy.setToolTip(_translate("Form", "Copy text (Ctrl+C)"))
        self.toolCopy.setShortcut(_translate("Form", "Ctrl+C"))
        self.toolCut.setToolTip(_translate("Form", "Cut text (Ctrl+X)"))
        self.toolCut.setText(_translate("Form", "..."))
        self.toolCut.setShortcut(_translate("Form", "Ctrl+X"))
        self.toolPaste.setToolTip(_translate("Form", "Paste text (Ctrl+V)"))
        self.toolPaste.setShortcut(_translate("Form", "Ctrl+V"))
        self.toolBold.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Bold text (Ctrl+B)</span></p></body></html>"))
        self.toolBold.setShortcut(_translate("Form", "Ctrl+B"))
        self.toolItalic.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-style:italic;\">Italic text (Ctrl+I)</span></p></body></html>"))
        self.toolItalic.setShortcut(_translate("Form", "Ctrl+I"))
        self.toolUnderline.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" text-decoration: underline;\">Underline text (Ctrl+U)</span></p></body></html>"))
        self.toolUnderline.setShortcut(_translate("Form", "Ctrl+U"))
        self.toolHeader.setToolTip(_translate("Form", "Add header (Ctrl+1)"))
        self.toolHeader.setShortcut(_translate("Form", "Ctrl+1"))
        self.toolOList.setToolTip(_translate("Form", "Unordered list"))
        self.toolOList.setText(_translate("Form", "..."))
        self.toolUList.setToolTip(_translate("Form", "Ordered list"))
        self.toolLink.setToolTip(_translate("Form", "Add link to text"))
        self.toolUnlink.setToolTip(_translate("Form", "Unlink text"))
        self.textEdit.setAccessibleName(_translate("Form", "Therapy plan"))
import icons_rc
