# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_entry.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 1046)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 901, 167))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 3, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 5, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 3, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 3, 5, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 5, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 4, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 5, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(860, 0, 31, 20))
        self.graphicsView.setObjectName("graphicsView")
        self.label_41 = QtWidgets.QLabel(self.frame)
        self.label_41.setGeometry(QtCore.QRect(740, 0, 121, 17))
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.frame, 2, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 700, 901, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 901, 271))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_4.addWidget(self.lineEdit_30, 1, 5, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 2, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 4, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 2, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 0, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_4.addWidget(self.lineEdit_27, 0, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 1, 2, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_4.addWidget(self.lineEdit_34, 1, 3, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_4.addWidget(self.lineEdit_37, 3, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_4.addWidget(self.lineEdit_32, 2, 3, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_4.addWidget(self.lineEdit_29, 1, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 1, 0, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_4.addWidget(self.lineEdit_36, 3, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 1, 4, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_4.addWidget(self.lineEdit_31, 2, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 3, 2, 1, 1)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout_4.addWidget(self.plainTextEdit_4, 4, 1, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_4.addWidget(self.lineEdit_33, 4, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 4, 2, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_4.addWidget(self.lineEdit_43, 0, 2, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_4.addWidget(self.lineEdit_44, 0, 5, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_4.addWidget(self.lineEdit_28, 0, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_53.setObjectName("label_53")
        self.gridLayout_4.addWidget(self.label_53, 0, 4, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 4, 4, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_4.addWidget(self.lineEdit_42, 4, 5, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 901, 271))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_7.addWidget(self.lineEdit_53, 1, 5, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_61.setObjectName("label_61")
        self.gridLayout_7.addWidget(self.label_61, 2, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_62.setObjectName("label_62")
        self.gridLayout_7.addWidget(self.label_62, 4, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_63.setObjectName("label_63")
        self.gridLayout_7.addWidget(self.label_63, 2, 2, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_64.setObjectName("label_64")
        self.gridLayout_7.addWidget(self.label_64, 0, 0, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_7.addWidget(self.lineEdit_54, 0, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_65.setObjectName("label_65")
        self.gridLayout_7.addWidget(self.label_65, 1, 2, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_7.addWidget(self.lineEdit_55, 1, 3, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_7.addWidget(self.lineEdit_56, 3, 3, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_7.addWidget(self.lineEdit_57, 2, 3, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_7.addWidget(self.lineEdit_58, 1, 1, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_66.setObjectName("label_66")
        self.gridLayout_7.addWidget(self.label_66, 3, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_67.setObjectName("label_67")
        self.gridLayout_7.addWidget(self.label_67, 1, 0, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_7.addWidget(self.lineEdit_59, 3, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_68.setObjectName("label_68")
        self.gridLayout_7.addWidget(self.label_68, 1, 4, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout_7.addWidget(self.lineEdit_60, 2, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_69.setObjectName("label_69")
        self.gridLayout_7.addWidget(self.label_69, 3, 2, 1, 1)
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.gridLayout_7.addWidget(self.plainTextEdit_6, 4, 1, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout_7.addWidget(self.lineEdit_61, 4, 3, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_70.setObjectName("label_70")
        self.gridLayout_7.addWidget(self.label_70, 4, 2, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout_7.addWidget(self.lineEdit_62, 0, 2, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout_7.addWidget(self.lineEdit_63, 0, 5, 1, 1)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.gridLayout_7.addWidget(self.lineEdit_64, 0, 3, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_71.setObjectName("label_71")
        self.gridLayout_7.addWidget(self.label_71, 0, 4, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_72.setObjectName("label_72")
        self.gridLayout_7.addWidget(self.label_72, 4, 4, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout_7.addWidget(self.lineEdit_65, 4, 5, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tabWidget.addTab(self.tab_15, "")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 210, 111, 17))
        self.label_12.setObjectName("label_12")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 230, 901, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 4, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_2.addWidget(self.lineEdit_15, 1, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 0, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 1, 1, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 0, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 2, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 4, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_2.addWidget(self.lineEdit_16, 1, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 320, 161, 17))
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 340, 901, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_3.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_3.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_3.addWidget(self.lineEdit_20, 1, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_3.addWidget(self.lineEdit_18, 0, 3, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_3.addWidget(self.lineEdit_21, 1, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 420, 191, 17))
        self.label_14.setObjectName("label_14")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 440, 901, 255))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 2, 2, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_5.addWidget(self.plainTextEdit, 2, 3, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_5.addWidget(self.lineEdit_26, 1, 3, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_5.addWidget(self.lineEdit_24, 0, 5, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_5.addWidget(self.lineEdit_22, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 0, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_5.addWidget(self.lineEdit_23, 0, 3, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_5.addWidget(self.lineEdit_25, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 2, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_5.addWidget(self.plainTextEdit_2, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 3, 2, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_5.addWidget(self.plainTextEdit_3, 3, 3, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_5.addWidget(self.radioButton_3, 4, 4, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_5.addWidget(self.radioButton_4, 4, 5, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 908, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuSave = QtWidgets.QMenu(self.menuBar)
        self.menuSave.setObjectName("menuSave")
        self.menuPrint = QtWidgets.QMenu(self.menuBar)
        self.menuPrint.setObjectName("menuPrint")
        self.menuRecord = QtWidgets.QMenu(self.menuBar)
        self.menuRecord.setObjectName("menuRecord")
        self.menuExport = QtWidgets.QMenu(self.menuBar)
        self.menuExport.setObjectName("menuExport")
        self.menuAssessment = QtWidgets.QMenu(self.menuBar)
        self.menuAssessment.setObjectName("menuAssessment")
        self.menuTools = QtWidgets.QMenu(self.menuAssessment)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menuBar)
        self.actionEdit_Record = QtWidgets.QAction(MainWindow)
        self.actionEdit_Record.setObjectName("actionEdit_Record")
        self.actionLock_Record = QtWidgets.QAction(MainWindow)
        self.actionLock_Record.setObjectName("actionLock_Record")
        self.actionExport_as_PDF = QtWidgets.QAction(MainWindow)
        self.actionExport_as_PDF.setObjectName("actionExport_as_PDF")
        self.actionExport_as_Word_document = QtWidgets.QAction(MainWindow)
        self.actionExport_as_Word_document.setObjectName("actionExport_as_Word_document")
        self.actionBatelle = QtWidgets.QAction(MainWindow)
        self.actionBatelle.setObjectName("actionBatelle")
        self.actionSensory = QtWidgets.QAction(MainWindow)
        self.actionSensory.setObjectName("actionSensory")
        self.actionOT = QtWidgets.QAction(MainWindow)
        self.actionOT.setObjectName("actionOT")
        self.actionPhysiotherapy = QtWidgets.QAction(MainWindow)
        self.actionPhysiotherapy.setObjectName("actionPhysiotherapy")
        self.actionBehaviour = QtWidgets.QAction(MainWindow)
        self.actionBehaviour.setObjectName("actionBehaviour")
        self.actionSpeech_Language = QtWidgets.QAction(MainWindow)
        self.actionSpeech_Language.setObjectName("actionSpeech_Language")
        self.actionResults = QtWidgets.QAction(MainWindow)
        self.actionResults.setObjectName("actionResults")
        self.actionPlan = QtWidgets.QAction(MainWindow)
        self.actionPlan.setObjectName("actionPlan")
        self.actionBattele = QtWidgets.QAction(MainWindow)
        self.actionBattele.setObjectName("actionBattele")
        self.actionSensory_2 = QtWidgets.QAction(MainWindow)
        self.actionSensory_2.setObjectName("actionSensory_2")
        self.actionPhysiotherapy_2 = QtWidgets.QAction(MainWindow)
        self.actionPhysiotherapy_2.setObjectName("actionPhysiotherapy_2")
        self.actionBehaviour_2 = QtWidgets.QAction(MainWindow)
        self.actionBehaviour_2.setObjectName("actionBehaviour_2")
        self.actionSpeech_and_Language = QtWidgets.QAction(MainWindow)
        self.actionSpeech_and_Language.setObjectName("actionSpeech_and_Language")
        self.menuRecord.addAction(self.actionEdit_Record)
        self.menuRecord.addAction(self.actionLock_Record)
        self.menuExport.addAction(self.actionExport_as_PDF)
        self.menuExport.addAction(self.actionExport_as_Word_document)
        self.menuTools.addAction(self.actionBattele)
        self.menuTools.addAction(self.actionSensory_2)
        self.menuTools.addAction(self.actionPhysiotherapy_2)
        self.menuTools.addAction(self.actionBehaviour_2)
        self.menuTools.addAction(self.actionSpeech_and_Language)
        self.menuAssessment.addAction(self.actionResults)
        self.menuAssessment.addAction(self.actionPlan)
        self.menuAssessment.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuRecord.menuAction())
        self.menuBar.addAction(self.menuSave.menuAction())
        self.menuBar.addAction(self.menuPrint.menuAction())
        self.menuBar.addAction(self.menuExport.menuAction())
        self.menuBar.addAction(self.menuAssessment.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Birth Place"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Date of Admission"))
        self.label_8.setText(_translate("MainWindow", "Family Name"))
        self.label.setText(_translate("MainWindow", "Hospital Name"))
        self.radioButton_2.setText(_translate("MainWindow", "Male"))
        self.label_7.setText(_translate("MainWindow", "Date of Birth"))
        self.label_4.setText(_translate("MainWindow", "Hospital Diagnosis"))
        self.label_3.setText(_translate("MainWindow", "Nationality"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_11.setText(_translate("MainWindow", "Gender"))
        self.radioButton.setText(_translate("MainWindow", "Female"))
        self.label_52.setText(_translate("MainWindow", "Primary Caregiver"))
        self.label_41.setText(_translate("MainWindow", "Record Number"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>ggg</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "Medicines"))
        self.label_39.setText(_translate("MainWindow", "Living with child?"))
        self.label_47.setText(_translate("MainWindow", "Work Address"))
        self.label_40.setText(_translate("MainWindow", "Email"))
        self.label_35.setText(_translate("MainWindow", "Given Names"))
        self.label_38.setText(_translate("MainWindow", "Occupation"))
        self.label_44.setText(_translate("MainWindow", "Phone No."))
        self.label_37.setText(_translate("MainWindow", "Education"))
        self.label_42.setText(_translate("MainWindow", "Workplace"))
        self.label_45.setText(_translate("MainWindow", "Work No."))
        self.label_36.setText(_translate("MainWindow", "Mailing PO Box"))
        self.label_53.setText(_translate("MainWindow", "Last Name"))
        self.label_51.setText(_translate("MainWindow", "Mailing PC "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Father"))
        self.label_61.setText(_translate("MainWindow", "Living with child?"))
        self.label_62.setText(_translate("MainWindow", "Work Address"))
        self.label_63.setText(_translate("MainWindow", "Email"))
        self.label_64.setText(_translate("MainWindow", "Given Names"))
        self.label_65.setText(_translate("MainWindow", "Occupation"))
        self.label_66.setText(_translate("MainWindow", "Phone No."))
        self.label_67.setText(_translate("MainWindow", "Education"))
        self.label_68.setText(_translate("MainWindow", "Workplace"))
        self.label_69.setText(_translate("MainWindow", "Work No."))
        self.label_70.setText(_translate("MainWindow", "Mailing PO Box"))
        self.label_71.setText(_translate("MainWindow", "Last Name"))
        self.label_72.setText(_translate("MainWindow", "Mailing PC "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mother"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Family"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Services"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Social Assist"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Residential"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Prenatal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "Birth History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("MainWindow", "Postnatal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("MainWindow", "Childhood"))
        self.label_6.setText(_translate("MainWindow", "Student Details"))
        self.label_12.setText(_translate("MainWindow", "Address Details"))
        self.label_15.setText(_translate("MainWindow", "Wallaya"))
        self.label_19.setText(_translate("MainWindow", "Lane No."))
        self.label_20.setText(_translate("MainWindow", "House No."))
        self.label_16.setText(_translate("MainWindow", "Village"))
        self.label_17.setText(_translate("MainWindow", "Block No."))
        self.label_18.setText(_translate("MainWindow", "Street"))
        self.label_13.setText(_translate("MainWindow", "Emergency Contact"))
        self.label_25.setText(_translate("MainWindow", "Office Phone No."))
        self.label_23.setText(_translate("MainWindow", "Mobile No."))
        self.label_22.setText(_translate("MainWindow", "Relation to student"))
        self.label_24.setText(_translate("MainWindow", "Home Phone No."))
        self.label_21.setText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "General Information"))
        self.label_32.setText(_translate("MainWindow", "Expectations"))
        self.label_26.setText(_translate("MainWindow", "First Language"))
        self.label_30.setText(_translate("MainWindow", "Reason for Referral"))
        self.label_28.setText(_translate("MainWindow", "Other Languages"))
        self.label_27.setText(_translate("MainWindow", "Second Language"))
        self.label_29.setText(_translate("MainWindow", "Referred by"))
        self.label_33.setText(_translate("MainWindow", "Challenges"))
        self.label_34.setText(_translate("MainWindow", "Remarks"))
        self.radioButton_3.setText(_translate("MainWindow", "Yes"))
        self.radioButton_4.setText(_translate("MainWindow", "No"))
        self.label_31.setText(_translate("MainWindow", "Do you have a domestic helper?"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuPrint.setTitle(_translate("MainWindow", "Print"))
        self.menuRecord.setTitle(_translate("MainWindow", "Record"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuAssessment.setTitle(_translate("MainWindow", "Assessment"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionEdit_Record.setText(_translate("MainWindow", "Edit Record"))
        self.actionLock_Record.setText(_translate("MainWindow", "Lock Record"))
        self.actionExport_as_PDF.setText(_translate("MainWindow", "Export as PDF"))
        self.actionExport_as_Word_document.setText(_translate("MainWindow", "Export as Word document"))
        self.actionBatelle.setText(_translate("MainWindow", "Batelle"))
        self.actionSensory.setText(_translate("MainWindow", "Sensory"))
        self.actionOT.setText(_translate("MainWindow", "OT"))
        self.actionPhysiotherapy.setText(_translate("MainWindow", "Physiotherapy"))
        self.actionBehaviour.setText(_translate("MainWindow", "Behaviour"))
        self.actionSpeech_Language.setText(_translate("MainWindow", "Speech and Language"))
        self.actionResults.setText(_translate("MainWindow", "Results"))
        self.actionPlan.setText(_translate("MainWindow", "Plan"))
        self.actionBattele.setText(_translate("MainWindow", "Battele"))
        self.actionSensory_2.setText(_translate("MainWindow", "Sensory"))
        self.actionPhysiotherapy_2.setText(_translate("MainWindow", "Physiotherapy"))
        self.actionBehaviour_2.setText(_translate("MainWindow", "Behaviour"))
        self.actionSpeech_and_Language.setText(_translate("MainWindow", "Speech and Language"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

